apiVersion: apps/v1
kind: Deployment
metdata:
  name: myapp-deployment
  lables:
    app: myapp

spec:                
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      name: nginx-2
      labels: 
        app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx 
